name: 'medicare_cclf_connector'
version: '0.1.2'
config-version: 2

profile: default

vars:
  demo_data_only: true

  ## Set the database and schema where raw CCLF data is stored
  input_database: tuva
  input_schema: raw

  claims_enabled: true

  ## Set to false if the CCLFA / CCLFB benefit enhancement and demonstration
  ## code files (parta_demo_codes, partb_demo_codes) are not available. The
  ## paid_reduced_by column in medical_claim will then be null.
  demo_codes_enabled: true

  ## Uncomment this variable if enrollment source is member months
  #  member_months_enrollment: true

model-paths: ["models"]
docs-paths: ["descriptions"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
   medicare_cclf_connector:
     final:
       +materialized: table
     intermediate:
       +materialized: table
     staging:
       +materialized: view
