name: 'medicare_cclf_connector'
version: '0.1.2'
config-version: 2

profile: default

vars:

  ## Set the database and schema where raw CCLF data is stored
  input_database: dev_ci_testing
  input_schema: cclf

  claims_enabled: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# models:
#   medicare_cclf_connector:
#     +database: default
#   the_tuva_project:
#     +database: default

# seeds:
#   +database: default

