
select distinct
cur_clm_uniq_id
--,clm_line_num
,bene_mbi_id
,bene_hic_num
,clm_type_cd
,clm_from_dt
,clm_thru_dt
--,rndrg_prvdr_type_cd
--,rndrg_prvdr_fips_st_cd
--,clm_prvdr_spclty_cd
--,clm_fed_type_srvc_cd
--,clm_pos_cd
--,clm_line_from_dt
--,clm_line_thru_dt
--,clm_line_hcpcs_cd
--,clm_line_cvrd_pd_amt
--,clm_line_prmry_pyr_cd
--,clm_line_dgns_cd
--,clm_rndrg_prvdr_tax_num
--,rndrg_prvdr_npi_num
,clm_carr_pmt_dnl_cd
--,clm_prcsg_ind_cd
,clm_adjsmt_type_cd
,clm_efctv_dt
,clm_idr_ld_dt
,clm_cntl_num
,bene_eqtbl_bic_hicn_num
--,clm_line_alowd_chrg_amt
--,clm_line_srvc_unit_qty
--,hcpcs_1_mdfr_cd
--,hcpcs_2_mdfr_cd
--,hcpcs_3_mdfr_cd
--,hcpcs_4_mdfr_cd
--,hcpcs_5_mdfr_cd
,clm_disp_cd
,clm_dgns_1_cd
,clm_dgns_2_cd
,clm_dgns_3_cd
,clm_dgns_4_cd
,clm_dgns_5_cd
,clm_dgns_6_cd
,clm_dgns_7_cd
,clm_dgns_8_cd
,dgns_prcdr_icd_ind
,clm_dgns_9_cd
,clm_dgns_10_cd
,clm_dgns_11_cd
,clm_dgns_12_cd
--,hcpcs_betos_cd
 From {{ var('partb_physicians')}} h