default:
    target: ci
    outputs:
      ci:
        type: databricks
        host: "${{ env_var('DATABRICKS_HOST') }"
        http_path: "${{ env_var('DATABRICKS_HTTP_PATH') }"
        token: "${{ env_var('DATABRICKS_TOKEN') }"
        catalog: 'hive_metastore'
        schema: ci_testing
        threads: 8
        connect_timeout: 60
        connect_retries: 3