select
      cast(cur_clm_uniq_id as {{ dbt.type_string() }}) as cur_clm_uniq_id
    , cast(clm_line_num as {{ dbt.type_string() }}) as clm_line_num
    , cast(bene_mbi_id as {{ dbt.type_string() }}) as bene_mbi_id
    , cast(bene_hic_num as {{ dbt.type_string() }}) as bene_hic_num
    , cast(clm_type_cd as {{ dbt.type_string() }}) as clm_type_cd
    , cast(clm_from_dt as {{ dbt.type_string() }}) as clm_from_dt
    , cast(clm_thru_dt as {{ dbt.type_string() }}) as clm_thru_dt
    , cast(rndrg_prvdr_type_cd as {{ dbt.type_string() }}) as rndrg_prvdr_type_cd
    , cast(rndrg_prvdr_fips_st_cd as {{ dbt.type_string() }}) as rndrg_prvdr_fips_st_cd
    , cast(clm_prvdr_spclty_cd as {{ dbt.type_string() }}) as clm_prvdr_spclty_cd
    , cast(clm_fed_type_srvc_cd as {{ dbt.type_string() }}) as clm_fed_type_srvc_cd
    , cast(clm_pos_cd as {{ dbt.type_string() }}) as clm_pos_cd
    , cast(clm_line_from_dt as {{ dbt.type_string() }}) as clm_line_from_dt
    , cast(clm_line_thru_dt as {{ dbt.type_string() }}) as clm_line_thru_dt
    , cast(clm_line_hcpcs_cd as {{ dbt.type_string() }}) as clm_line_hcpcs_cd
    , cast(clm_line_cvrd_pd_amt as {{ dbt.type_string() }}) as clm_line_cvrd_pd_amt
    , cast(clm_line_prmry_pyr_cd as {{ dbt.type_string() }}) as clm_line_prmry_pyr_cd
    , cast(clm_line_dgns_cd as {{ dbt.type_string() }}) as clm_line_dgns_cd
    , cast(clm_rndrg_prvdr_tax_num as {{ dbt.type_string() }}) as clm_rndrg_prvdr_tax_num
    , cast(rndrg_prvdr_npi_num as {{ dbt.type_string() }}) as rndrg_prvdr_npi_num
    , cast(clm_carr_pmt_dnl_cd as {{ dbt.type_string() }}) as clm_carr_pmt_dnl_cd
    , cast(clm_prcsg_ind_cd as {{ dbt.type_string() }}) as clm_prcsg_ind_cd
    , cast(clm_adjsmt_type_cd as {{ dbt.type_string() }}) as clm_adjsmt_type_cd
    , cast(clm_efctv_dt as {{ dbt.type_string() }}) as clm_efctv_dt
    , cast(clm_idr_ld_dt as {{ dbt.type_string() }}) as clm_idr_ld_dt
    , cast(clm_cntl_num as {{ dbt.type_string() }}) as clm_cntl_num
    , cast(bene_eqtbl_bic_hicn_num as {{ dbt.type_string() }}) as bene_eqtbl_bic_hicn_num
    , cast(clm_line_alowd_chrg_amt as {{ dbt.type_string() }}) as clm_line_alowd_chrg_amt
    , cast(clm_line_srvc_unit_qty as {{ dbt.type_string() }}) as clm_line_srvc_unit_qty
    , cast(hcpcs_1_mdfr_cd as {{ dbt.type_string() }}) as hcpcs_1_mdfr_cd
    , cast(hcpcs_2_mdfr_cd as {{ dbt.type_string() }}) as hcpcs_2_mdfr_cd
    , cast(hcpcs_3_mdfr_cd as {{ dbt.type_string() }}) as hcpcs_3_mdfr_cd
    , cast(hcpcs_4_mdfr_cd as {{ dbt.type_string() }}) as hcpcs_4_mdfr_cd
    , cast(hcpcs_5_mdfr_cd as {{ dbt.type_string() }}) as hcpcs_5_mdfr_cd
    , cast(clm_disp_cd as {{ dbt.type_string() }}) as clm_disp_cd
    , cast(clm_dgns_1_cd as {{ dbt.type_string() }}) as clm_dgns_1_cd
    , cast(clm_dgns_2_cd as {{ dbt.type_string() }}) as clm_dgns_2_cd
    , cast(clm_dgns_3_cd as {{ dbt.type_string() }}) as clm_dgns_3_cd
    , cast(clm_dgns_4_cd as {{ dbt.type_string() }}) as clm_dgns_4_cd
    , cast(clm_dgns_5_cd as {{ dbt.type_string() }}) as clm_dgns_5_cd
    , cast(clm_dgns_6_cd as {{ dbt.type_string() }}) as clm_dgns_6_cd
    , cast(clm_dgns_7_cd as {{ dbt.type_string() }}) as clm_dgns_7_cd
    , cast(clm_dgns_8_cd as {{ dbt.type_string() }}) as clm_dgns_8_cd
    , cast(dgns_prcdr_icd_ind as {{ dbt.type_string() }}) as dgns_prcdr_icd_ind
    , cast(clm_dgns_9_cd as {{ dbt.type_string() }}) as clm_dgns_9_cd
    , cast(clm_dgns_10_cd as {{ dbt.type_string() }}) as clm_dgns_10_cd
    , cast(clm_dgns_11_cd as {{ dbt.type_string() }}) as clm_dgns_11_cd
    , cast(clm_dgns_12_cd as {{ dbt.type_string() }}) as clm_dgns_12_cd
    , cast(hcpcs_betos_cd as {{ dbt.type_string() }}) as hcpcs_betos_cd
    , cast(file_name as {{ dbt.type_string() }}) as file_name
    , cast(ingest_datetime as {{ dbt.type_timestamp() }}) as ingest_datetime
from {{ source('medicare_cclf','partb_physicians') }}