select a.bene_mbi_id
     , a.bene_hic_num
     , a.bene_1st_name
     , a.bene_last_name
     , a.bene_sex_cd
     , a.bene_brth_dt
     , a.bene_death_dt
     , a.geo_ssa_cnty_cd_name
     , a.geo_ssa_state_name
     , a.state_county_cd
     , a.in_va_max
     , a.va_tin
     , a.va_npi
     , a.cba_flag
     , a.assignment_type
     , a.assigned_before
     , a.asg_status
     , a.partd_months
     , a.enrollflag1
     , a.enrollflag2
     , a.enrollflag3
     , a.enrollflag4
     , a.enrollflag5
     , a.enrollflag6
     , a.enrollflag7
     , a.enrollflag8
     , a.enrollflag9
     , a.enrollflag10
     , a.enrollflag11
     , a.enrollflag12
     , a.hcc_version
     , a.hcc_col_1
     , a.hcc_col_2
     , a.hcc_col_3
     , a.hcc_col_4
     , a.hcc_col_5
     , a.hcc_col_6
     , a.hcc_col_7
     , a.hcc_col_8
     , a.hcc_col_9
     , a.hcc_col_10
     , a.hcc_col_11
     , a.hcc_col_12
     , a.hcc_col_13
     , a.hcc_col_14
     , a.hcc_col_15
     , a.hcc_col_16
     , a.hcc_col_17
     , a.hcc_col_18
     , a.hcc_col_19
     , a.hcc_col_20
     , a.hcc_col_21
     , a.hcc_col_22
     , a.hcc_col_23
     , a.hcc_col_24
     , a.hcc_col_25
     , a.hcc_col_26
     , a.hcc_col_27
     , a.hcc_col_28
     , a.hcc_col_29
     , a.hcc_col_30
     , a.hcc_col_31
     , a.hcc_col_32
     , a.hcc_col_33
     , a.hcc_col_34
     , a.hcc_col_35
     , a.hcc_col_36
     , a.hcc_col_37
     , a.hcc_col_38
     , a.hcc_col_39
     , a.hcc_col_40
     , a.hcc_col_41
     , a.hcc_col_42
     , a.hcc_col_43
     , a.hcc_col_44
     , a.hcc_col_45
     , a.hcc_col_46
     , a.hcc_col_47
     , a.hcc_col_48
     , a.hcc_col_49
     , a.hcc_col_50
     , a.hcc_col_51
     , a.hcc_col_52
     , a.hcc_col_53
     , a.hcc_col_54
     , a.hcc_col_55
     , a.hcc_col_56
     , a.hcc_col_57
     , a.hcc_col_58
     , a.hcc_col_59
     , a.hcc_col_60
     , a.hcc_col_61
     , a.hcc_col_62
     , a.hcc_col_63
     , a.hcc_col_64
     , a.hcc_col_65
     , a.hcc_col_66
     , a.hcc_col_67
     , a.hcc_col_68
     , a.hcc_col_69
     , a.hcc_col_70
     , a.hcc_col_71
     , a.hcc_col_72
     , a.hcc_col_73
     , a.hcc_col_74
     , a.hcc_col_75
     , a.hcc_col_76
     , a.hcc_col_77
     , a.hcc_col_78
     , a.hcc_col_79
     , a.hcc_col_80
     , a.hcc_col_81
     , a.hcc_col_82
     , a.hcc_col_83
     , a.hcc_col_84
     , a.hcc_col_85
     , a.hcc_col_86
     , a.hcc_col_87
     , a.hcc_col_88
     , a.hcc_col_89
     , a.hcc_col_90
     , a.bene_rsk_r_scre_01
     , a.bene_rsk_r_scre_02
     , a.bene_rsk_r_scre_03
     , a.bene_rsk_r_scre_04
     , a.bene_rsk_r_scre_05
     , a.bene_rsk_r_scre_06
     , a.bene_rsk_r_scre_07
     , a.bene_rsk_r_scre_08
     , a.bene_rsk_r_scre_09
     , a.bene_rsk_r_scre_10
     , a.bene_rsk_r_scre_11
     , a.bene_rsk_r_scre_12
     , a.esrd_score
     , a.dis_score
     , a.agdu_score
     , a.agnd_score
     , a.dem_esrd_score
     , a.dem_dis_score
     , a.dem_agdu_score
     , a.dem_agnd_score
     , a.new_enrollee
     , a.lti_status
     , a.bene_race_cd

from {{ source('medicare_cclf','aalr_2024') }} as a
