name: biweekly_dbt_v1.3.0_redshift_build_full_refresh

on:
  workflow_dispatch:
  schedule:
    # This job will run at midnight on the 1st and 15th of the month
    - cron: '0 0 1,15 * *'

env:
  DBT_REDSHIFT_CI_HOST: ${{ secrets.DBT_REDSHIFT_CI_HOST }}
  DBT_REDSHIFT_CI_USER: ${{ secrets.DBT_REDSHIFT_CI_USER }}
  DBT_REDSHIFT_CI_PASSWORD: ${{ secrets.DBT_REDSHIFT_CI_PASSWORD }}
  DBT_REDSHIFT_CI_PORT: ${{ secrets.DBT_REDSHIFT_CI_PORT }}

  
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.3.0
        with:
          dbt_command: "dbt deps --profiles-dir ./integration_tests/profiles/redshift"
          
      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.3.0
        with:
          dbt_command: "dbt debug --profiles-dir ./integration_tests/profiles/redshift"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.3.0
        with:
          dbt_command: 'dbt build --full-refresh --profiles-dir ./integration_tests/profiles/redshift --vars {"tuva_database":"dev_ci_testing","input_database":"dev_ci_testing","input_schema":"cclf","tuva_schema_prefix":"cclf"}'

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash
